### ISSUE TITLE
Reminder Management

### ISSUE THREAD

**Issue by diziara** [TurqW/LongSphinx#70]
The ability to list, delete, and maybe even edit existing reminders. List and delete are the important ones, but if edit isn't annoying to add, it would be helpful.

**Comment by MageCity** [comment]
"list" is done as of 8bb93a7184c18851bb5a4b0f725346eab3f1e4e9 , I'll probably close this once I add delete, because "editing" is a surprisingly nebulous concept and is probably better handled by just deleting and recreating instead.

**Comment by WaltWh** [comment]
Deletes are implemented in the with-pycord-alpha branch and will be released along with the great migration to slash commands.
