### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by TurqW** [TurqW/LongSphinx#98]
With Pycord this should be reasonably straightforward, but labor intensive (involves manually migrating all modules)

Current overall status report on the framework migration (Slash Commands, etc):
**COMMANDS**:
```
remind:      Done
reminders:   Done
color:       Done
makesprint:  Done
joinsprint:  Done
sprintwords: Done
notice:      Done
summon:      Done
pet:         Done
getseed:     Done
rep:         Done
saveroll:    Done
search:      Done
clearroll:   Done
gen:         Done
roll:        Done
rolls:       Done
pic:         Done
pick:        Done
role:        Done
readme:
ban:         Done
```

**OTHER FEATURES**:
```
scheduled messages:          Done
auto-moderation:             Done
limit commands by channel:   Done
autoreact (runes etc):       Done
autoreply (squirt Hammy):    Done
assign role on member join:  Done
report member leaving:       Done
embed colors:                Done
```

These other features should actually mostly be unchanged from LongSphinx 1.0; that said, many of them are impossible if my access to the "messages" intent gets shut off, which is still uncertain, and thus they're being treated as lower priority.

**NEW/IMPROVED FEATURES**
(which mostly came about by necessity of a different interaction paradigm)
```
Reminder management - you can delete them now!
Destructive actions now ask for a confirmation!
 (generally. Tell me if I missed any.)
Better management of dice macros
First draft of an actual user config system
Better interfaces, friendlier messages, all-around better UX
```

**Comment by WaltWh** [comment]
The only thing left is help commands, which should be less necessary than before now that we have autocompletes, parameter prompting, etc.. Could potentially even leave them off entirely?

**Comment by diziara** [comment]
I like having a help option, but if you want to migrate it to a link to a page on github since the auto complete should lower the need for it, that might be a low cost alternative.
